# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perceptron.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perceptron.proto',
  package='nebulalink.perceptron',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10perceptron.proto\x12\x15nebulalink.perceptron\"\x1e\n\x06Point2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\")\n\x06Point3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\xd2\x05\n\nPerceptron\x12\x11\n\tDevide_Id\x18\x01 \x01(\t\x12\x16\n\x0e\x44\x65vide_Is_True\x18\x02 \x01(\x08\x12\x14\n\x0cNumber_Frame\x18\x03 \x01(\x05\x12\x41\n\x11Object_Class_Type\x18\x04 \x01(\x0e\x32&.nebulalink.perceptron.Perceptron.Type\x12\x11\n\tObject_Id\x18\x05 \x01(\x05\x12.\n\x07Point3f\x18\x06 \x01(\x0b\x32\x1d.nebulalink.perceptron.Point3\x12\x19\n\x11Object_Confidence\x18\x07 \x01(\x02\x12\x14\n\x0cObject_Speed\x18\x08 \x01(\x02\x12\x1b\n\x13Object_acceleration\x18\t \x01(\x02\x12\x14\n\x0cObject_Width\x18\n \x01(\x02\x12\x15\n\rObject_Length\x18\x0b \x01(\x02\x12\x15\n\rObject_Height\x18\x0c \x01(\x02\x12\x18\n\x10Object_Longitude\x18\r \x01(\x01\x12\x17\n\x0fObject_Latitude\x18\x0e \x01(\x01\x12\x37\n\tObject_NS\x18\x0f \x01(\x0e\x32$.nebulalink.perceptron.Perceptron.NS\x12\x37\n\tObject_WE\x18\x10 \x01(\x0e\x32$.nebulalink.perceptron.Perceptron.EW\x12\x12\n\nTime_stamp\x18\x11 \x01(\x03\x12\x18\n\x10Object_Direction\x18\x12 \x01(\x02\x12\x12\n\nObject_Yaw\x18\x13 \x01(\x02\x12\x12\n\nis_tracker\x18\x14 \x01(\x08\"H\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nPEDESTRIAN\x10\x01\x12\x0b\n\x07\x42ICYCLE\x10\x02\x12\x07\n\x03\x43\x41R\x10\x03\x12\r\n\tTRUCK_BUS\x10\x04\"\x12\n\x02NS\x12\x05\n\x01N\x10\x00\x12\x05\n\x01S\x10\x01\"\x12\n\x02\x45W\x12\x05\n\x01\x45\x10\x00\x12\x05\n\x01W\x10\x01\"F\n\rPerceptronSet\x12\x35\n\nperceptron\x18\x01 \x03(\x0b\x32!.nebulalink.perceptron.Perceptronb\x06proto3'
)



_PERCEPTRON_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='nebulalink.perceptron.Perceptron.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PEDESTRIAN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BICYCLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRUCK_BUS', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=729,
  serialized_end=801,
)
_sym_db.RegisterEnumDescriptor(_PERCEPTRON_TYPE)

_PERCEPTRON_NS = _descriptor.EnumDescriptor(
  name='NS',
  full_name='nebulalink.perceptron.Perceptron.NS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='N', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=803,
  serialized_end=821,
)
_sym_db.RegisterEnumDescriptor(_PERCEPTRON_NS)

_PERCEPTRON_EW = _descriptor.EnumDescriptor(
  name='EW',
  full_name='nebulalink.perceptron.Perceptron.EW',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='W', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=823,
  serialized_end=841,
)
_sym_db.RegisterEnumDescriptor(_PERCEPTRON_EW)


_POINT2 = _descriptor.Descriptor(
  name='Point2',
  full_name='nebulalink.perceptron.Point2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='nebulalink.perceptron.Point2.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='nebulalink.perceptron.Point2.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)


_POINT3 = _descriptor.Descriptor(
  name='Point3',
  full_name='nebulalink.perceptron.Point3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='nebulalink.perceptron.Point3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='nebulalink.perceptron.Point3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='nebulalink.perceptron.Point3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=116,
)


_PERCEPTRON = _descriptor.Descriptor(
  name='Perceptron',
  full_name='nebulalink.perceptron.Perceptron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Devide_Id', full_name='nebulalink.perceptron.Perceptron.Devide_Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Devide_Is_True', full_name='nebulalink.perceptron.Perceptron.Devide_Is_True', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Number_Frame', full_name='nebulalink.perceptron.Perceptron.Number_Frame', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Class_Type', full_name='nebulalink.perceptron.Perceptron.Object_Class_Type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Id', full_name='nebulalink.perceptron.Perceptron.Object_Id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Point3f', full_name='nebulalink.perceptron.Perceptron.Point3f', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Confidence', full_name='nebulalink.perceptron.Perceptron.Object_Confidence', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Speed', full_name='nebulalink.perceptron.Perceptron.Object_Speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_acceleration', full_name='nebulalink.perceptron.Perceptron.Object_acceleration', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Width', full_name='nebulalink.perceptron.Perceptron.Object_Width', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Length', full_name='nebulalink.perceptron.Perceptron.Object_Length', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Height', full_name='nebulalink.perceptron.Perceptron.Object_Height', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Longitude', full_name='nebulalink.perceptron.Perceptron.Object_Longitude', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Latitude', full_name='nebulalink.perceptron.Perceptron.Object_Latitude', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_NS', full_name='nebulalink.perceptron.Perceptron.Object_NS', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_WE', full_name='nebulalink.perceptron.Perceptron.Object_WE', index=15,
      number=16, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time_stamp', full_name='nebulalink.perceptron.Perceptron.Time_stamp', index=16,
      number=17, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Direction', full_name='nebulalink.perceptron.Perceptron.Object_Direction', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Object_Yaw', full_name='nebulalink.perceptron.Perceptron.Object_Yaw', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_tracker', full_name='nebulalink.perceptron.Perceptron.is_tracker', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERCEPTRON_TYPE,
    _PERCEPTRON_NS,
    _PERCEPTRON_EW,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=841,
)


_PERCEPTRONSET = _descriptor.Descriptor(
  name='PerceptronSet',
  full_name='nebulalink.perceptron.PerceptronSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='perceptron', full_name='nebulalink.perceptron.PerceptronSet.perceptron', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=843,
  serialized_end=913,
)

_PERCEPTRON.fields_by_name['Object_Class_Type'].enum_type = _PERCEPTRON_TYPE
_PERCEPTRON.fields_by_name['Point3f'].message_type = _POINT3
_PERCEPTRON.fields_by_name['Object_NS'].enum_type = _PERCEPTRON_NS
_PERCEPTRON.fields_by_name['Object_WE'].enum_type = _PERCEPTRON_EW
_PERCEPTRON_TYPE.containing_type = _PERCEPTRON
_PERCEPTRON_NS.containing_type = _PERCEPTRON
_PERCEPTRON_EW.containing_type = _PERCEPTRON
_PERCEPTRONSET.fields_by_name['perceptron'].message_type = _PERCEPTRON
DESCRIPTOR.message_types_by_name['Point2'] = _POINT2
DESCRIPTOR.message_types_by_name['Point3'] = _POINT3
DESCRIPTOR.message_types_by_name['Perceptron'] = _PERCEPTRON
DESCRIPTOR.message_types_by_name['PerceptronSet'] = _PERCEPTRONSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point2 = _reflection.GeneratedProtocolMessageType('Point2', (_message.Message,), {
  'DESCRIPTOR' : _POINT2,
  '__module__' : 'perceptron_pb2'
  # @@protoc_insertion_point(class_scope:nebulalink.perceptron.Point2)
  })
_sym_db.RegisterMessage(Point2)

Point3 = _reflection.GeneratedProtocolMessageType('Point3', (_message.Message,), {
  'DESCRIPTOR' : _POINT3,
  '__module__' : 'perceptron_pb2'
  # @@protoc_insertion_point(class_scope:nebulalink.perceptron.Point3)
  })
_sym_db.RegisterMessage(Point3)

Perceptron = _reflection.GeneratedProtocolMessageType('Perceptron', (_message.Message,), {
  'DESCRIPTOR' : _PERCEPTRON,
  '__module__' : 'perceptron_pb2'
  # @@protoc_insertion_point(class_scope:nebulalink.perceptron.Perceptron)
  })
_sym_db.RegisterMessage(Perceptron)

PerceptronSet = _reflection.GeneratedProtocolMessageType('PerceptronSet', (_message.Message,), {
  'DESCRIPTOR' : _PERCEPTRONSET,
  '__module__' : 'perceptron_pb2'
  # @@protoc_insertion_point(class_scope:nebulalink.perceptron.PerceptronSet)
  })
_sym_db.RegisterMessage(PerceptronSet)


# @@protoc_insertion_point(module_scope)
